# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Zoul
                                 A QGIS plugin
 No dana, only zoul
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-06-29
        copyright            : (C) 2026 by François Botcazou
        email                : francois.botcazou@proton.me
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'François Botcazou'
__date__ = '2026-06-29'
__copyright__ = '(C) 2026 by François Botcazou'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Zoul class from file Zoul.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Zoul import ZoulPlugin
    return ZoulPlugin()
